# Para começar com as atualizações de versão do Dependabot, você precisará especificar qual
# ecossistemas de pacotes a serem atualizados e onde os manifestos do pacote estão localizados.
# Consulte a documentação para todas as opções de configuração:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # Consulte a documentação para valores possíveis
    directory: "/" # Localização dos manifestos do pacote
    schedule:
      interval: "weekly"
